

- name: Move SSL certs
  tags: django
  template:
    src: "{{ item.ssl_fullchain }}"
    dest: "{{ item.ssl_path }}/"
    owner: root
    group: root
  with_items: "{{ websites }}"
  notify: reload nginx

- name: Move SSL keys
  tags: django
  template:
    src: "{{ item.ssl_key }}"
    dest: "{{ item.ssl_path }}/"
    owner: root
    group: root
  with_items: "{{ websites }}"
  notify: reload nginx

- name: Move thecodebase.tech-*
  tags: django
  template:
    src: "{{ item }}"
    dest: "/etc/nginx/ssl/thecodebase.tech/"
    owner: root
    group: root
  with_items:
    - thecodebase.tech-fullchain.pem
    - thecodebase.tech-key.pem

  notify: reload nginx

